	SUBROUTINE TEMPO(IBOBO,ISEED)
	!esta subrotina serve para estimar 
	!o tempo de processamento do programa
	USE PORTLIB
	IMPLICIT NONE
	INTEGER IBOBO
	INTEGER ITIME3,ITIME2,ITIME1 !   CONTADOR DE TEMPO
	INTEGER ISEED
	
	TEMPOS: SELECT CASE(IBOBO)
	CASE(0)   !   INICIA A CONTAGEM DE TEMPO
		itime1 = TIME()
		ISEED=ITIME1
		!print *, 'TEMPO INICIAL ', itime1
	CASE(1)	  !   TERMINA CONTAGEM DO TEMPO
		itime2 = TIME()
		ITIME3=ITIME2-ITIME1
		!print *, 'TEMPO TOTAL ', itime3,'SEG'
	END SELECT TEMPOS
	RETURN
	END